# Generated by Django 5.1.1 on 2025-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0014_remove_usersession_login_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleStateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('code_verifier', models.CharField(max_length=255)),
            ],
        ),
    ]
