SUPPORTED_FEATURES = [
    "random_feature",
    "speed",
    "acceleration",
    "deceleration",
    "jerk",
    "waiting_period",
    "waiting_interval",
    "waiting_distance",
    "separation",
    "intersection",
    "collision",
    "mttcp",
    "thw",
    "ttc",
    "drac",
]
