__title__ = 'xnattagger'
__description__ = 'XNAT Tagger'
__url__ = 'https://github.com/harvard-nrg/xnattagger'
__version__ = '0.8.0'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
