# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .start_render_job_response_error_output_data import StartRenderJobResponseErrorOutputData
from .start_render_job_response_error_output_metadata import StartRenderJobResponseErrorOutputMetadata


class StartRenderJobResponseErrorOutput(UniversalBaseModel):
    data: StartRenderJobResponseErrorOutputData
    metadata: StartRenderJobResponseErrorOutputMetadata

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
