"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.acp.internal.event_pb2
import ansys.api.acp.v0.base_pb2
import grpc
import typing

class EventServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    EventStream: grpc.UnaryStreamMultiCallable[
        ansys.api.acp.v0.base_pb2.Empty,
        ansys.api.acp.internal.event_pb2.Event] = ...


class EventServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def EventStream(self,
        request: ansys.api.acp.v0.base_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> typing.Iterator[ansys.api.acp.internal.event_pb2.Event]: ...


def add_EventServiceServicer_to_server(servicer: EventServiceServicer, server: grpc.Server) -> None: ...
