from time import sleep
from functions import clear_terminal, theEnd
def haluctination():
    clear_terminal()
    print("\nYou: \"What’s the worst that could happen? It’s just a berry.\"")
    sleep(1)
    print("*CHOMP*")
    sleep(2)
    print('\nThe bush gasps: "YOU IMBECILE! THAT WAS MY BRAIN NODE!"')
    sleep(1)
    print('KNIGHT.GPT: "Warning. Unknown neuroactive compounds detected in digestive tract."')
    sleep(1)
    print("KNIGHT.GPT: \"Analyzing... Analyzing... wait, are those your shoelaces arguing with gravity?\"")
    sleep(1)
    print("\nEverything melts into color. The sky giggles. A nearby rock claims it’s your father.")
    sleep(2)
    print("You are now trapped in a recursive hallucination loop.")
    sleep(1)
    print("You keep rebooting—but only into weirder, fruit-themed realities.")
    sleep(2)
    print("\n💤 BAD ENDING: You become king of the Jellyfish Parliament.")
    sleep(0.5)
    print("They unanimously impeach you on day two. Game over.")
    theEnd()
