"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from speakeasy.new_openapi.types import BaseModel
from typing_extensions import Annotated, TypedDict


class SimpleObjectTypedDict(TypedDict):
    str_: str
    r"""A string property."""


class SimpleObject(BaseModel):
    str_: Annotated[str, pydantic.Field(alias="str")]
    r"""A string property."""
