# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/acp/v0/analysis_ply.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.acp.v0 import base_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_base__pb2
from ansys.api.acp.v0 import enum_types_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_enum__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ansys/api/acp/v0/analysis_ply.proto\x12\x1d\x61nsys.api.acp.v0.analysis_ply\x1a\x1b\x61nsys/api/acp/v0/base.proto\x1a!ansys/api/acp/v0/enum_types.proto\"\xbb\x01\n\nProperties\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.ansys.api.acp.v0.enum_types.StatusType\x12\x35\n\x08material\x18\x02 \x01(\x0b\x32#.ansys.api.acp.v0.base.ResourcePath\x12\x11\n\tthickness\x18\x03 \x01(\x01\x12\r\n\x05\x61ngle\x18\x04 \x01(\x01\x12\x1b\n\x13\x61\x63tive_in_post_mode\x18\x05 \x01(\x08\"{\n\nObjectInfo\x12.\n\x04info\x18\x01 \x01(\x0b\x32 .ansys.api.acp.v0.base.BasicInfo\x12=\n\nproperties\x18\x02 \x01(\x0b\x32).ansys.api.acp.v0.analysis_ply.Properties\"G\n\tListReply\x12:\n\x07objects\x18\x01 \x03(\x0b\x32).ansys.api.acp.v0.analysis_ply.ObjectInfo2\xba\x01\n\rObjectService\x12T\n\x04List\x12\".ansys.api.acp.v0.base.ListRequest\x1a(.ansys.api.acp.v0.analysis_ply.ListReply\x12S\n\x03Get\x12!.ansys.api.acp.v0.base.GetRequest\x1a).ansys.api.acp.v0.analysis_ply.ObjectInfoB>Z<github.com/ansys/ansys-api-acp/ansys/api/acp/v0/analysis_plyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ansys.api.acp.v0.analysis_ply_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/ansys/ansys-api-acp/ansys/api/acp/v0/analysis_ply'
  _PROPERTIES._serialized_start=135
  _PROPERTIES._serialized_end=322
  _OBJECTINFO._serialized_start=324
  _OBJECTINFO._serialized_end=447
  _LISTREPLY._serialized_start=449
  _LISTREPLY._serialized_end=520
  _OBJECTSERVICE._serialized_start=523
  _OBJECTSERVICE._serialized_end=709
# @@protoc_insertion_point(module_scope)
