# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/acp/v0/lookup_table_column_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ansys/api/acp/v0/lookup_table_column_type.proto\x12)ansys.api.acp.v0.lookup_table_column_type*4\n\tValueType\x12\n\n\x06SCALAR\x10\x00\x12\r\n\tDIRECTION\x10\x01\x12\x0c\n\x08LOCATION\x10\x02\x42JZHgithub.com/ansys/ansys-api-acp/ansys/api/acp/v0/lookup_table_column_typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ansys.api.acp.v0.lookup_table_column_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgithub.com/ansys/ansys-api-acp/ansys/api/acp/v0/lookup_table_column_type'
  _VALUETYPE._serialized_start=94
  _VALUETYPE._serialized_end=146
# @@protoc_insertion_point(module_scope)
