# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/acp/v0/lookup_table_1d_column.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.acp.v0 import base_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_base__pb2
from ansys.api.acp.v0 import unit_system_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_unit__system__pb2
from ansys.api.acp.v0 import array_types_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_array__types__pb2
from ansys.api.acp.v0 import lookup_table_column_type_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_lookup__table__column__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-ansys/api/acp/v0/lookup_table_1d_column.proto\x12\'ansys.api.acp.v0.lookup_table_1d_column\x1a\x1b\x61nsys/api/acp/v0/base.proto\x1a\"ansys/api/acp/v0/unit_system.proto\x1a\"ansys/api/acp/v0/array_types.proto\x1a/ansys/api/acp/v0/lookup_table_column_type.proto\"\xd4\x01\n\nProperties\x12H\n\nvalue_type\x18\x01 \x01(\x0e\x32\x34.ansys.api.acp.v0.lookup_table_column_type.ValueType\x12\x43\n\x0e\x64imension_type\x18\x02 \x01(\x0e\x32+.ansys.api.acp.v0.unit_system.DimensionType\x12\x37\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32).ansys.api.acp.v0.array_types.DoubleArray\"\x85\x01\n\nObjectInfo\x12.\n\x04info\x18\x01 \x01(\x0b\x32 .ansys.api.acp.v0.base.BasicInfo\x12G\n\nproperties\x18\x02 \x01(\x0b\x32\x33.ansys.api.acp.v0.lookup_table_1d_column.Properties\"Q\n\tListReply\x12\x44\n\x07objects\x18\x01 \x03(\x0b\x32\x33.ansys.api.acp.v0.lookup_table_1d_column.ObjectInfo\"\xa6\x01\n\rCreateRequest\x12>\n\x0f\x63ollection_path\x18\x01 \x01(\x0b\x32%.ansys.api.acp.v0.base.CollectionPath\x12\x0c\n\x04name\x18\x02 \x01(\t\x12G\n\nproperties\x18\x03 \x01(\x0b\x32\x33.ansys.api.acp.v0.lookup_table_1d_column.Properties2\x84\x04\n\rObjectService\x12^\n\x04List\x12\".ansys.api.acp.v0.base.ListRequest\x1a\x32.ansys.api.acp.v0.lookup_table_1d_column.ListReply\x12]\n\x03Get\x12!.ansys.api.acp.v0.base.GetRequest\x1a\x33.ansys.api.acp.v0.lookup_table_1d_column.ObjectInfo\x12o\n\x03Put\x12\x33.ansys.api.acp.v0.lookup_table_1d_column.ObjectInfo\x1a\x33.ansys.api.acp.v0.lookup_table_1d_column.ObjectInfo\x12L\n\x06\x44\x65lete\x12$.ansys.api.acp.v0.base.DeleteRequest\x1a\x1c.ansys.api.acp.v0.base.Empty\x12u\n\x06\x43reate\x12\x36.ansys.api.acp.v0.lookup_table_1d_column.CreateRequest\x1a\x33.ansys.api.acp.v0.lookup_table_1d_column.ObjectInfoBHZFgithub.com/ansys/ansys-api-acp/ansys/api/acp/v0/lookup_table_1d_columnb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ansys.api.acp.v0.lookup_table_1d_column_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFgithub.com/ansys/ansys-api-acp/ansys/api/acp/v0/lookup_table_1d_column'
  _PROPERTIES._serialized_start=241
  _PROPERTIES._serialized_end=453
  _OBJECTINFO._serialized_start=456
  _OBJECTINFO._serialized_end=589
  _LISTREPLY._serialized_start=591
  _LISTREPLY._serialized_end=672
  _CREATEREQUEST._serialized_start=675
  _CREATEREQUEST._serialized_end=841
  _OBJECTSERVICE._serialized_start=844
  _OBJECTSERVICE._serialized_end=1360
# @@protoc_insertion_point(module_scope)
