# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_manifest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from . import record_auditinfo_pb2 as record__auditinfo__pb2
from . import instrument_group_pb2 as instrument__group__pb2
from . import instrument_type_pb2 as instrument__type__pb2
from . import instrument_measurement_capability_pb2 as instrument__measurement__capability__pb2
from . import localization_pb2 as localization__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='instrument_manifest.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\034ONE.Models.CSharp.Instrument'),
  serialized_pb=_b('\n\x19instrument_manifest.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16record_auditinfo.proto\x1a\x16instrument_group.proto\x1a\x15instrument_type.proto\x1a\'instrument_measurement_capability.proto\x1a\x12localization.proto\"\xde\x02\n\x12InstrumentManifest\x12-\n\x07version\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12)\n\x0finstrumentGroup\x18\x02 \x01(\x0b\x32\x10.InstrumentGroup\x12\'\n\x0einstrumentType\x18\x03 \x01(\x0b\x32\x0f.InstrumentType\x12(\n\x02id\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12I\n\x1finstrumentMeasurementCapability\x18\n \x01(\x0b\x32 .InstrumentMeasurementCapability\x12%\n\rlocalizations\x18\x0e \x01(\x0b\x32\x0e.Localizations\x12)\n\x0frecordAuditInfo\x18\x63 \x01(\x0b\x32\x10.RecordAuditInfoB\x1f\xaa\x02\x1cONE.Models.CSharp.Instrumentb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,record__auditinfo__pb2.DESCRIPTOR,instrument__group__pb2.DESCRIPTOR,instrument__type__pb2.DESCRIPTOR,instrument__measurement__capability__pb2.DESCRIPTOR,localization__pb2.DESCRIPTOR,])




_INSTRUMENTMANIFEST = _descriptor.Descriptor(
  name='InstrumentManifest',
  full_name='InstrumentManifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='InstrumentManifest.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrumentGroup', full_name='InstrumentManifest.instrumentGroup', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrumentType', full_name='InstrumentManifest.instrumentType', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='InstrumentManifest.id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrumentMeasurementCapability', full_name='InstrumentManifest.instrumentMeasurementCapability', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='localizations', full_name='InstrumentManifest.localizations', index=5,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordAuditInfo', full_name='InstrumentManifest.recordAuditInfo', index=6,
      number=99, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=544,
)

_INSTRUMENTMANIFEST.fields_by_name['version'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTMANIFEST.fields_by_name['instrumentGroup'].message_type = instrument__group__pb2._INSTRUMENTGROUP
_INSTRUMENTMANIFEST.fields_by_name['instrumentType'].message_type = instrument__type__pb2._INSTRUMENTTYPE
_INSTRUMENTMANIFEST.fields_by_name['id'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTMANIFEST.fields_by_name['instrumentMeasurementCapability'].message_type = instrument__measurement__capability__pb2._INSTRUMENTMEASUREMENTCAPABILITY
_INSTRUMENTMANIFEST.fields_by_name['localizations'].message_type = localization__pb2._LOCALIZATIONS
_INSTRUMENTMANIFEST.fields_by_name['recordAuditInfo'].message_type = record__auditinfo__pb2._RECORDAUDITINFO
DESCRIPTOR.message_types_by_name['InstrumentManifest'] = _INSTRUMENTMANIFEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentManifest = _reflection.GeneratedProtocolMessageType('InstrumentManifest', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTMANIFEST,
  '__module__' : 'instrument_manifest_pb2'
  # @@protoc_insertion_point(class_scope:InstrumentManifest)
  })
_sym_db.RegisterMessage(InstrumentManifest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
