"""
db4e/Constants/Components.py

    Database 4 Everything
    Author: Nadim-Daniel Ghaznavi 
    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
    GitHub: https://github.com/NadimGhaznavi/db4e
    License: GPL 3.0
"""

from db4e.Constants.Fields import (
    ANY_IP_FIELD, CHAIN_FIELD, CONFIG_FIELD, DATA_DIR_FIELD,
    DONATION_WALLET_FIELD, FIELD_FIELD, GROUP_FIELD, HEALTH_MSGS_FIELD, 
    IN_PEERS_FIELD,
    INSTALL_DIR_FIELD, INSTANCE_FIELD, IP_ADDR_FIELD, LABEL_FIELD,
    LOG_LEVEL_FIELD, LOG_NAME_FIELD, MAX_LOG_FILES_FIELD,
    MAX_LOG_SIZE_FIELD, NUM_THREADS_FIELD, OUT_PEERS_FIELD,
    P2P_BIND_PORT_FIELD, PARENT_ID_FIELD, PRIORITY_NODE_1_FIELD,
    PRIORITY_NODE_2_FIELD, PRIORITY_PORT_1_FIELD, PRIORITY_PORT_2_FIELD,
    REMOTE_FIELD, RPC_BIND_PORT_FIELD, SHOW_TIME_STATS_FIELD,
    STRATUM_PORT_FIELD, USER_FIELD, USER_WALLET_FIELD, VALUE_FIELD,
    VENDOR_DIR_FIELD, VERSION_FIELD, ZMQ_PUB_PORT_FIELD, ZMQ_RPC_PORT_FIELD
)
from db4e.Constants.Labels import (
    ANY_IP_LABEL, CHAIN_LABEL, CONFIG_LABEL, DATA_DIR_LABEL, DONATIONS_WALLET_LABEL,
    GROUP_LABEL, HEALTH_MSGS_LABEL, IN_PEERS_LABEL, INSTALL_DIR_LABEL, INSTANCE_LABEL, IP_ADDR_LABEL,
    LOG_LEVEL_LABEL, LOG_NAME_LABEL, MAX_LOG_FILES_LABEL, MAX_LOG_SIZE_LABEL,
    NUM_THREADS_LABEL, OUT_PEERS_LABEL, P2P_BIND_PORT_LABEL, PARENT_ID_LABEL,
    PRIORITY_NODE_1_LABEL, PRIORITY_NODE_2_LABEL, PRIORITY_PORT_1_LABEL,
    PRIORITY_PORT_2_LABEL, REMOTE_LABEL, RPC_BIND_PORT_LABEL, SHOW_TIME_STATS_LABEL,
    STRATUM_PORT_LABEL, USER_LABEL, USER_WALLET_LABEL, VENDOR_DIR_LABEL, VERSION_LABEL,
    ZMQ_PUB_PORT_LABEL, ZMQ_RPC_PORT_LABEL
)
from db4e.Constants.Defaults import (
    ANY_IP_DEFAULT, CHAIN_DEFAULT, DONATION_WALLET_DEFAULT, IN_PEERS_DEFAULT,
    LOG_LEVEL_DEFAULT, MAX_LOG_FILES_DEFAULT, MAX_LOG_SIZE_DEFAULT,
    MONEROD_VERSION_DEFAULT, NUM_THREADS_DEFAULT, OUT_PEERS_DEFAULT,
    P2P_BIND_PORT_DEFAULT, PRIORITY_NODE_1_DEFAULT, PRIORITY_NODE_2_DEFAULT,
    RPC_BIND_PORT_DEFAULT, SHOW_TIME_STATS_FIELD_DEFAULT, STRATUM_PORT_DEFAULT,
    ZMQ_PUB_PORT_DEFAULT, ZMQ_RPC_PORT_DEFAULT
)

def make_component(field, label, default_value=""):
    return {
        FIELD_FIELD: field,
        LABEL_FIELD: label,
        VALUE_FIELD: default_value
    }

ANY_IP = make_component(ANY_IP_FIELD, ANY_IP_LABEL, ANY_IP_DEFAULT)

CHAIN = make_component(CHAIN_FIELD, CHAIN_LABEL, CHAIN_DEFAULT)

CONFIG = make_component(CONFIG_FIELD, CONFIG_LABEL)

DATA_DIR = make_component(DATA_DIR_FIELD, DATA_DIR_LABEL)

DONATION_WALLET = make_component(
    DONATION_WALLET_FIELD, DONATIONS_WALLET_LABEL, DONATION_WALLET_DEFAULT)

GROUP = make_component(GROUP_FIELD, GROUP_LABEL)

IN_PEERS = make_component(IN_PEERS_FIELD, IN_PEERS_LABEL, IN_PEERS_DEFAULT)

INSTALL_DIR = make_component(INSTALL_DIR_FIELD, INSTALL_DIR_LABEL)

INSTANCE = make_component(INSTANCE_FIELD, INSTANCE_LABEL)

IP_ADDR = make_component(IP_ADDR_FIELD, IP_ADDR_LABEL)

LOCAL = make_component(REMOTE_FIELD, REMOTE_LABEL, False)

LOG_LEVEL = make_component(LOG_LEVEL_FIELD, LOG_LEVEL_LABEL, LOG_LEVEL_DEFAULT)

LOG_NAME = make_component(LOG_NAME_FIELD, LOG_NAME_LABEL)

MAX_LOG_FILES = make_component(
    MAX_LOG_FILES_FIELD, MAX_LOG_FILES_LABEL, MAX_LOG_FILES_DEFAULT)

MAX_LOG_SIZE = make_component(
    MAX_LOG_SIZE_FIELD, MAX_LOG_SIZE_LABEL, MAX_LOG_SIZE_DEFAULT)

NUM_THREADS = make_component(NUM_THREADS_FIELD, NUM_THREADS_LABEL, NUM_THREADS_DEFAULT)

OUT_PEERS = make_component(OUT_PEERS_FIELD, OUT_PEERS_LABEL, OUT_PEERS_DEFAULT)

P2P_BIND_PORT = make_component(
    P2P_BIND_PORT_FIELD, P2P_BIND_PORT_LABEL, P2P_BIND_PORT_DEFAULT)

PARENT_ID = make_component(PARENT_ID_FIELD, PARENT_ID_LABEL)

PRIORITY_NODE_1 = make_component(
    PRIORITY_NODE_1_FIELD, PRIORITY_NODE_1_LABEL, PRIORITY_NODE_1_DEFAULT)

PRIORITY_NODE_2 = make_component(
    PRIORITY_NODE_2_FIELD, PRIORITY_NODE_2_LABEL, PRIORITY_NODE_2_DEFAULT)

PRIORITY_PORT_1 = make_component(
    PRIORITY_PORT_1_FIELD, PRIORITY_PORT_1_LABEL, P2P_BIND_PORT_DEFAULT)

PRIORITY_PORT_2 = make_component(
    PRIORITY_PORT_2_FIELD, PRIORITY_PORT_2_LABEL, P2P_BIND_PORT_DEFAULT)

REMOTE = make_component(REMOTE_FIELD, REMOTE_LABEL, True)

RPC_BIND_PORT = make_component(
    RPC_BIND_PORT_FIELD, RPC_BIND_PORT_LABEL, RPC_BIND_PORT_DEFAULT)

SHOW_TIME_STATS = make_component(
    SHOW_TIME_STATS_FIELD, SHOW_TIME_STATS_LABEL, SHOW_TIME_STATS_FIELD_DEFAULT)

STRATUM_PORT = make_component(
    STRATUM_PORT_FIELD, STRATUM_PORT_LABEL, STRATUM_PORT_DEFAULT)

VERSION = make_component(VERSION_FIELD, VERSION_LABEL, MONEROD_VERSION_DEFAULT)

USER = make_component(USER_FIELD, USER_LABEL)

USER_WALLET = make_component(USER_WALLET_FIELD, USER_WALLET_LABEL)

VENDOR_DIR = make_component(VENDOR_DIR_FIELD, VENDOR_DIR_LABEL)

ZMQ_PUB_PORT = make_component(
    ZMQ_PUB_PORT_FIELD, ZMQ_PUB_PORT_LABEL, ZMQ_PUB_PORT_DEFAULT)
ZMQ_RPC_PORT = make_component(
    ZMQ_RPC_PORT_FIELD, ZMQ_RPC_PORT_LABEL, ZMQ_RPC_PORT_DEFAULT)
