print("╔────────────────────────────────── WELCOME ──────────────────────────────────╗")
print("|                   ▁ ▂ ▄ ▅ ▆ ▇ █   AutoCAD    █ ▇ ▆ ▅ ▄ ▂ ▁                  |")
print("|         AutoCAD is a Python library designed for automating AutoCAD         |")
print("|         workflows,enabling efficient drawing manipulations, custom          |")
print("|             scripting, and automation of repetitive CAD tasks               |")
print("|                               using Python.                                 |")
print("|  github: https://github.com/Jones-peter                    By - JonesPeter  |")
print("|                                                                             |")
print("╚──────────────────────────Unlimited CAD Automation───────────────────────────╝")
print(f"Version - 0.1.10")