from __future__ import annotations
from typing import Any, Optional, List, Type, TypeVar, Tuple
import numpy as np
from numpy.typing import NDArray

T = TypeVar('T')


class IndirRemovalPolicy:
    RemoveInvalidCols: int = ...
    RemoveInvalidRows: int = ...

class LineColorType:
    PerVert: int = ...
    Solid: int = ...

class MeshColorType:
    Normal: int = ...
    NormalViewCoords: int = ...
    PerVert: int = ...
    Solid: int = ...
    Texture: int = ...
    UV: int = ...

class PointColorType:
    PerVert: int = ...
    Solid: int = ...

class SplatType:
    Avg: int = ...
    Sum: int = ...

