from enum import Enum

DEFAULT_TRACE_ACTIVITIES = ["CPU", "CUDA"]
MINIMUM_PACKAGES = ["torch", "requests", "git+https://github.com/Herdora/chisel.git@dev"]
ENV_CACHY_ENABLED = "CACHY_ENABLED"

TRACE_DIR = "traces"
REPO_NAME = "chisel"

CHISEL_BACKEND_RUN_ENV_KEY = "CHISEL_BACKEND_RUN"
CHISEL_JOB_ID_ENV_KEY = "CHISEL_JOB_ID"
CHISEL_API_KEY_ENV_KEY = "CHISEL_API_KEY"
CHISEL_BACKEND_URL_ENV_KEY = "CHISEL_BACKEND_URL"
CHISEL_BACKEND_APP_NAME_ENV_KEY = "CHISEL_BACKEND_APP_NAME"

# CHISEL_BACKEND_URL = "http://localhost:8000"
CHISEL_BACKEND_URL = "https://api.keysandcaches.com"


class GPUType(Enum):
    A100_80GB_1 = "A100-80GB:1"
    A100_80GB_2 = "A100-80GB:2"
    A100_80GB_4 = "A100-80GB:4"
    A100_80GB_8 = "A100-80GB:8"
