# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clavata.cerberus.v1 import cerberus_pb2 as clavata_dot_cerberus_dot_v1_dot_cerberus__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in clavata/cerberus/v1/cerberus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CerberusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeImage = channel.unary_unary(
                '/cerberus.matcher.v1.CerberusService/AnalyzeImage',
                request_serializer=clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.AnalyzeImageRequest.SerializeToString,
                response_deserializer=clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.AnalyzeImageResponse.FromString,
                _registered_method=True)
        self.ReloadReferenceSet = channel.unary_unary(
                '/cerberus.matcher.v1.CerberusService/ReloadReferenceSet',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.ReloadReferenceSetResponse.FromString,
                _registered_method=True)


class CerberusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadReferenceSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CerberusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.AnalyzeImageRequest.FromString,
                    response_serializer=clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.AnalyzeImageResponse.SerializeToString,
            ),
            'ReloadReferenceSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadReferenceSet,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.ReloadReferenceSetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerberus.matcher.v1.CerberusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerberus.matcher.v1.CerberusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CerberusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerberus.matcher.v1.CerberusService/AnalyzeImage',
            clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.AnalyzeImageRequest.SerializeToString,
            clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.AnalyzeImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadReferenceSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerberus.matcher.v1.CerberusService/ReloadReferenceSet',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clavata_dot_cerberus_dot_v1_dot_cerberus__pb2.ReloadReferenceSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
