class Zebra:
    def __init__(self, queue: str | None = ...) -> None: ...
    def output(self, commands: str | bytes, encoding: str = ...) -> None: ...
    def print_config_label(self) -> None: ...
    def getqueues(self) -> list[str]: ...
    def setqueue(self, queue: str) -> None: ...
    def setup(
        self,
        direct_thermal: bool = ...,
        label_height: int | None = ...,
        label_width: int | None = ...,
    ) -> None: ...
    def reset_default(self) -> None: ...
    def reset(self) -> None: ...
    def autosense(self) -> None: ...
    def store_graphic(self, name: str, filename: str) -> None: ...
    def print_graphic(
        self,
        x: int,
        y: int,
        width: int,
        length: int,
        data: bytes,
        qty: int,
    ) -> None: ...
