from typing import Any, Callable, Self

Key = str | int

class RMap:
    def __init__(self, factory: Callable[[], Any] | None = None) -> None: ...
    def __new__(cls, factory: Callable[[], Any] | None = None) -> Self: ...
    async def set(self, key: Key, value: Any) -> None: ...
    async def pop(self, key: Key) -> None: ...
    async def get(self, key: Key) -> Any | None: ...
    async def keys(self) -> list[Key]: ...
    async def values(self) -> list[Any]: ...
    async def items(self) -> list[tuple[Key, Any]]: ...

class RCacheMap:
    def __init__(self) -> None: ...
    def __new__(cls) -> Self: ...
    async def set(self, key: Key, value: Any, ttl: float) -> None: ...
    async def pop(self, key: Key) -> None: ...
    async def get(self, key: Key) -> Any | None: ...
    async def pop_expired(self) -> None: ...
