# Generated by Django 5.1.1 on 2025-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0009_alter_usersession_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='login_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
