#python
#data_glover_config.py

RGB_DATAGLOVE_LEFT = {"FINGER_1":"0,0,0","FINGER_2":"0,0,0","FINGER_3":"0,0,0","FINGER_4":"0,0,0","FINGER_5":"0,0,0"}
RGB_DATAGLOVE_RIGHT =  {"FINGER_1":"0,0,0","FINGER_2":"0,0,0","FINGER_3":"0,0,0","FINGER_4":"0,0,0","FINGER_5":"0,0,0"}
RGB_DATAGLOVE = RGB_DATAGLOVE_RIGHT.copy()
DATAGLOVE_CURSOR = {"RGB_DATAGLOVE_SIDE":RGB_DATAGLOVE_LEFT,"RGB_LEFT_CLICK":RGB_DATAGLOVE["FINGER_2"], "RGB_RIGHT_CLICK":RGB_DATAGLOVE["FINGER_3"],"RGB_SCROOL_DOWN":RGB_DATAGLOVE["FINGER_1"],"RGB_SCROOL_UP":RGB_DATAGLOVE["FINGER_5"],"RGB_GLOVE_COLOR:":"255,255,255"}

def set_dataglove_left(FINGER_1,FINGER_2,FINGER_3,FINGER_4,FINGER_5):
	RGB_DATAGLOVE_LEFT = {"FINGER_1":FINGER_1,"FINGER_2":FINGER_2,"FINGER_3":FINGER_3,"FINGER_4":FINGER_4,"FINGER_5":FINGER_5}

def set_dataglove_right(FINGER_1,FINGER_2,FINGER_3,FINGER_4,FINGER_5):
	RGB_DATAGLOVE_RIGHT = {"FINGER_1":FINGER_1,"FINGER_2":FINGER_2,"FINGER_3":FINGER_3,"FINGER_4":FINGER_4,"FINGER_5":FINGER_5}

def set_dataglove_side(_side):
	if(side == 'LEFT'):
		RGB_DATAGLOVE = RGB_DATAGLOVE_LEFT.copy()
	else:
		RGB_DATAGLOVE = RGB_DATAGLOVE_RIGHT.copy()

def get_dataglove():
	return RGB_DATAGLOVE

def get_dataglove_cursor():
	return DATAGLOVE_CURSOR