"""
db4e/Templates/db/SoftwareSystems.py

    Database 4 Everything
    Author: Nadim-Daniel Ghaznavi 
    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
    GitHub: https://github.com/NadimGhaznavi/db4e
    License: GPL 3.0

This module contains templates for the Mongo deployment record types.
"""

from datetime import datetime

from db4e.Constants.Defaults import (
MONEROD_VERSION_DEFAULT, P2POOL_VERSION_DEFAULT,
    XMRIG_VERSION_DEFAULT, DB4E_VERSION_DEFAULT
)

from db4e.Constants.Fields import (
    COMPONENTS_FIELD, DB4E_FIELD, ELEMENT_TYPE_FIELD, HEALTH_MSGS_FIELD,
    MONEROD_FIELD, MONEROD_REMOTE_FIELD, NAME_FIELD, P2POOL_FIELD, P2POOL_REMOTE_FIELD,
    VERSION_FIELD, XMRIG_FIELD)
from db4e.Constants.Labels import (
    DB4E_LABEL, MONEROD_LABEL, P2POOL_LABEL, XMRIG_LABEL)
from db4e.Constants.Components import (
    ANY_IP, CHAIN, CONFIG, DATA_DIR, DONATION_WALLET, GROUP, IN_PEERS, 
    INSTALL_DIR, INSTANCE, LOCAL, LOG_LEVEL, LOG_NAME, MAX_LOG_FILES, 
    MAX_LOG_SIZE, NUM_THREADS, OUT_PEERS, P2P_BIND_PORT, PARENT_ID, PRIORITY_NODE_1,
    PRIORITY_NODE_2, PRIORITY_PORT_1, PRIORITY_PORT_2, REMOTE, RPC_BIND_PORT,
    SHOW_TIME_STATS, STRATUM_PORT, USER, USER_WALLET, VENDOR_DIR, ZMQ_PUB_PORT,
    ZMQ_RPC_PORT, IP_ADDR)

## Each of the templates represents an instance of a CWM Software System

# Db4E Core 
Db4E_Template = {
    NAME_FIELD: DB4E_LABEL,
    ELEMENT_TYPE_FIELD: DB4E_FIELD,
    VERSION_FIELD: DB4E_VERSION_DEFAULT,
    HEALTH_MSGS_FIELD: [],
    COMPONENTS_FIELD: [
        DONATION_WALLET, GROUP, INSTALL_DIR, USER, USER_WALLET, VENDOR_DIR
    ],
    }

# Monero Daemon Instance
MoneroD_Template = {
    NAME_FIELD: MONEROD_LABEL,
    ELEMENT_TYPE_FIELD: MONEROD_FIELD,
    VERSION_FIELD: MONEROD_VERSION_DEFAULT,
    HEALTH_MSGS_FIELD: [],
    COMPONENTS_FIELD: [
        CONFIG, DATA_DIR, IN_PEERS, INSTANCE, LOCAL, LOG_LEVEL, LOG_NAME, 
        MAX_LOG_FILES, MAX_LOG_SIZE, OUT_PEERS, P2P_BIND_PORT, PRIORITY_NODE_1, 
        PRIORITY_NODE_2, PRIORITY_PORT_1, PRIORITY_PORT_2, RPC_BIND_PORT, SHOW_TIME_STATS,
        ZMQ_PUB_PORT, ZMQ_RPC_PORT],
    }

# Remote Monero Daemon Instance
MoneroD_Remote_Template = {
    NAME_FIELD: MONEROD_LABEL,
    ELEMENT_TYPE_FIELD: MONEROD_REMOTE_FIELD,
    HEALTH_MSGS_FIELD: [],
    COMPONENTS_FIELD: [
        INSTANCE, REMOTE, RPC_BIND_PORT, IP_ADDR, ZMQ_PUB_PORT],
} 

# P2Pool Instance
P2Pool_Template = {
    NAME_FIELD: P2POOL_LABEL,
    ELEMENT_TYPE_FIELD: P2POOL_FIELD,
    VERSION_FIELD: P2POOL_VERSION_DEFAULT,
    HEALTH_MSGS_FIELD: [],
    COMPONENTS_FIELD: [
        ANY_IP, CHAIN, CONFIG, IN_PEERS, INSTANCE, LOCAL, LOG_LEVEL, PARENT_ID,
        OUT_PEERS, P2P_BIND_PORT, STRATUM_PORT, USER_WALLET],
    }

# Remote P2Pool Instance
P2Pool_Remote_Template = {
    NAME_FIELD: P2POOL_LABEL,
    ELEMENT_TYPE_FIELD: P2POOL_REMOTE_FIELD,
    HEALTH_MSGS_FIELD: [],
    COMPONENTS_FIELD: [
        INSTANCE, REMOTE, IP_ADDR, STRATUM_PORT],
    }

# XMRig Instance
XMRig_Template = {
    NAME_FIELD: XMRIG_LABEL,
    ELEMENT_TYPE_FIELD: XMRIG_FIELD,
    VERSION_FIELD: XMRIG_VERSION_DEFAULT,
    HEALTH_MSGS_FIELD: [],
    COMPONENTS_FIELD: [
        CONFIG, INSTANCE, LOCAL, NUM_THREADS, PARENT_ID],
    }
