from typing import Tuple

from dev.coatl.helper.types import AnyStr
from java.awt import Color
from java.util import EventObject
from javax.swing import JComponent

def chooseColor(initialColor: Color, dialogTitle: AnyStr = ...) -> Color: ...
def convertPointToScreen(x: int, y: int, event: EventObject) -> Tuple[int, int]: ...
def getQuality(component: JComponent, propertyName: AnyStr) -> int: ...
def openDiagnostics() -> None: ...
