# Generated by Django 4.2.23 on 2025-08-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milindustry', '0002_industrycharacter_industrycharacterskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSlotsUsage',
            fields=[
                ('industry_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_slots_usage', serialize=False, to='milindustry.industrycharacter')),
                ('manufacturing_used', models.PositiveSmallIntegerField(default=0)),
                ('reaction_used', models.PositiveSmallIntegerField(default=0)),
                ('research_used', models.PositiveSmallIntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
