# orbitlab/core/crypto.pyi

from typing import Any, Dict, Optional
from pathlib import Path
from Crypto.PublicKey.RSA import RsaKey

def firmar_dill(dill_path: Path, hash_algoritmo: str = ...) -> Path: ...
def validar_firma(dill_path: Path) -> bool: ...
def encrypt_hybrid(data: Any, **opts: Any) -> Dict[str, Any]: ...
def decrypt_hybrid(encrypted: Dict[str, Any], **opts: Any) -> Any: ...
def load_public_key() -> RsaKey: ...
def load_private_key() -> RsaKey: ...
def hash_text(password: str, encoding: str = ...) -> str: ...
def verify_hash_text(text: str, hashed: str, encoding: str = ...) -> bool: ...
def generate_rsa_keys(
    bits: int = ...,
    password: Optional[bytes] = ...,
    verbose: bool = ...
) -> Dict[str, str]: ...
