# Generated by Django 5.2 on 2025-05-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0010_remove_assistant_max_tokens_thread_max_tokens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openaifile",
            name="file_id",
        ),
    ]
