# Generated by Django 5.2 on 2025-06-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0016_vectorstorepool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vectorstorepool",
            name="vector_stores",
        ),
        migrations.AddField(
            model_name="vectorstorepool",
            name="vector_stores",
            field=models.ManyToManyField(
                blank=True, to="django_ragamuffin.vectorstore"
            ),
        ),
    ]
