# Generated by Django 5.2 on 2025-07-20 07:46

import django.core.files.storage
import django_ragamuffin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0025_assistant_unique_name_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaifile",
            name="file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    "/tmp/openaifiles", base_url="/media/"
                ),
                upload_to=django_ragamuffin.models.hashed_upload_to,
                validators=[django_ragamuffin.models.validate_file_extension],
            ),
        ),
    ]
