# Generated by Django 5.2 on 2025-07-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0027_alter_openaifile_file"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="thread",
            name="unique_thread",
        ),
    ]
