"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import ansys.api.acp.v0.base_pb2
import ansys.api.acp.v0.enum_types_pb2
import ansys.api.acp.v0.solid_model_pb2
import ansys.api.acp.v0.unit_system_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Properties(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    UNIT_SYSTEM_FIELD_NUMBER: builtins.int
    EXTERNAL_PATH_FIELD_NUMBER: builtins.int
    DELETE_BAD_ELEMENTS_FIELD_NUMBER: builtins.int
    WARPING_LIMIT_FIELD_NUMBER: builtins.int
    MINIMUM_VOLUME_FIELD_NUMBER: builtins.int
    CUT_OFF_MATERIAL_FIELD_NUMBER: builtins.int
    EXPORT_SETTINGS_FIELD_NUMBER: builtins.int
    status: ansys.api.acp.v0.enum_types_pb2.StatusType.ValueType = ...
    """GENERAL PROPERTIES
    read only
    """

    locked: builtins.bool = ...
    """read only"""

    active: builtins.bool = ...
    format: ansys.api.acp.v0.enum_types_pb2.FileFormat.ValueType = ...
    """SOURCE PROPERTIES"""

    unit_system: ansys.api.acp.v0.unit_system_pb2.UnitSystemType.ValueType = ...
    external_path: typing.Text = ...
    delete_bad_elements: builtins.bool = ...
    """ELEMENT QUALITY PROPERTIES"""

    warping_limit: builtins.float = ...
    minimum_volume: builtins.float = ...
    @property
    def cut_off_material(self) -> ansys.api.acp.v0.base_pb2.ResourcePath:
        """CUT-OFF PROPERTIES"""
        pass
    @property
    def export_settings(self) -> ansys.api.acp.v0.solid_model_pb2.ExportSettings:
        """EXPORT PROPERTIES
        The following properties are not supported (ignored) for imported solid
        models:
        - write_degenerated_elements
        - transfer_all_sets
        - transferred_element_sets
        - transferred_edge_sets
        """
        pass
    def __init__(self,
        *,
        status : ansys.api.acp.v0.enum_types_pb2.StatusType.ValueType = ...,
        locked : builtins.bool = ...,
        active : builtins.bool = ...,
        format : ansys.api.acp.v0.enum_types_pb2.FileFormat.ValueType = ...,
        unit_system : ansys.api.acp.v0.unit_system_pb2.UnitSystemType.ValueType = ...,
        external_path : typing.Text = ...,
        delete_bad_elements : builtins.bool = ...,
        warping_limit : builtins.float = ...,
        minimum_volume : builtins.float = ...,
        cut_off_material : typing.Optional[ansys.api.acp.v0.base_pb2.ResourcePath] = ...,
        export_settings : typing.Optional[ansys.api.acp.v0.solid_model_pb2.ExportSettings] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cut_off_material",b"cut_off_material","export_settings",b"export_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["active",b"active","cut_off_material",b"cut_off_material","delete_bad_elements",b"delete_bad_elements","export_settings",b"export_settings","external_path",b"external_path","format",b"format","locked",b"locked","minimum_volume",b"minimum_volume","status",b"status","unit_system",b"unit_system","warping_limit",b"warping_limit"]) -> None: ...
global___Properties = Properties

class ObjectInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INFO_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> ansys.api.acp.v0.base_pb2.BasicInfo: ...
    @property
    def properties(self) -> global___Properties: ...
    def __init__(self,
        *,
        info : typing.Optional[ansys.api.acp.v0.base_pb2.BasicInfo] = ...,
        properties : typing.Optional[global___Properties] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["info",b"info","properties",b"properties"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["info",b"info","properties",b"properties"]) -> None: ...
global___ObjectInfo = ObjectInfo

class ListReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OBJECTS_FIELD_NUMBER: builtins.int
    @property
    def objects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ObjectInfo]: ...
    def __init__(self,
        *,
        objects : typing.Optional[typing.Iterable[global___ObjectInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["objects",b"objects"]) -> None: ...
global___ListReply = ListReply

class CreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    COLLECTION_PATH_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    @property
    def collection_path(self) -> ansys.api.acp.v0.base_pb2.CollectionPath: ...
    name: typing.Text = ...
    @property
    def properties(self) -> global___Properties: ...
    def __init__(self,
        *,
        collection_path : typing.Optional[ansys.api.acp.v0.base_pb2.CollectionPath] = ...,
        name : typing.Text = ...,
        properties : typing.Optional[global___Properties] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["collection_path",b"collection_path","properties",b"properties"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["collection_path",b"collection_path","name",b"name","properties",b"properties"]) -> None: ...
global___CreateRequest = CreateRequest

class RefreshRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESOURCE_PATH_FIELD_NUMBER: builtins.int
    @property
    def resource_path(self) -> ansys.api.acp.v0.base_pb2.ResourcePath: ...
    def __init__(self,
        *,
        resource_path : typing.Optional[ansys.api.acp.v0.base_pb2.ResourcePath] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_path",b"resource_path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["resource_path",b"resource_path"]) -> None: ...
global___RefreshRequest = RefreshRequest

class ImportInitialMeshRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESOURCE_PATH_FIELD_NUMBER: builtins.int
    @property
    def resource_path(self) -> ansys.api.acp.v0.base_pb2.ResourcePath: ...
    def __init__(self,
        *,
        resource_path : typing.Optional[ansys.api.acp.v0.base_pb2.ResourcePath] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_path",b"resource_path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["resource_path",b"resource_path"]) -> None: ...
global___ImportInitialMeshRequest = ImportInitialMeshRequest
