# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.acp.v0 import base_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_base__pb2
from ansys.api.acp.v0 import model_pb2 as ansys_dot_api_dot_acp_dot_v0_dot_model__pb2


class ObjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/List',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.ListRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ListReply.FromString,
                )
        self.Get = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/Get',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.GetRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
                )
        self.Put = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/Put',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
                )
        self.Delete = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/Delete',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.DeleteRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
                )
        self.Update = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/Update',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.UpdateRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
                )
        self.LoadFromFile = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/LoadFromFile',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.LoadFromFileRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
                )
        self.LoadFromFEFile = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/LoadFromFEFile',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.LoadFromFEFileRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
                )
        self.SaveToFile = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/SaveToFile',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveToFileRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
                )
        self.SaveAnalysisModel = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/SaveAnalysisModel',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveAnalysisModelRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
                )
        self.SaveShellCompositeDefinitions = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/SaveShellCompositeDefinitions',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveShellCompositeDefinitionsRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
                )
        self.ExportHDF5CompositeCAE = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/ExportHDF5CompositeCAE',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ExportHDF5CompositeCAERequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
                )
        self.ImportHDF5CompositeCAE = channel.unary_unary(
                '/ansys.api.acp.v0.model.ObjectService/ImportHDF5CompositeCAE',
                request_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ImportHDF5CompositeCAERequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
                )


class ObjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadFromFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadFromFEFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveToFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveAnalysisModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveShellCompositeDefinitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportHDF5CompositeCAE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportHDF5CompositeCAE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.ListRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ListReply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.GetRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.DeleteRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.UpdateRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.SerializeToString,
            ),
            'LoadFromFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadFromFile,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.LoadFromFileRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.SerializeToString,
            ),
            'LoadFromFEFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadFromFEFile,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.LoadFromFEFileRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.SerializeToString,
            ),
            'SaveToFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveToFile,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveToFileRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.SerializeToString,
            ),
            'SaveAnalysisModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveAnalysisModel,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveAnalysisModelRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.SerializeToString,
            ),
            'SaveShellCompositeDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveShellCompositeDefinitions,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveShellCompositeDefinitionsRequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.SerializeToString,
            ),
            'ExportHDF5CompositeCAE': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportHDF5CompositeCAE,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ExportHDF5CompositeCAERequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.SerializeToString,
            ),
            'ImportHDF5CompositeCAE': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportHDF5CompositeCAE,
                    request_deserializer=ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ImportHDF5CompositeCAERequest.FromString,
                    response_serializer=ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.acp.v0.model.ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/List',
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.ListRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/Get',
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.GetRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/Put',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/Delete',
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.DeleteRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/Update',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.UpdateRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadFromFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/LoadFromFile',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.LoadFromFileRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadFromFEFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/LoadFromFEFile',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.LoadFromFEFileRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ObjectInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveToFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/SaveToFile',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveToFileRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveAnalysisModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/SaveAnalysisModel',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveAnalysisModelRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveShellCompositeDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/SaveShellCompositeDefinitions',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.SaveShellCompositeDefinitionsRequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportHDF5CompositeCAE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/ExportHDF5CompositeCAE',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ExportHDF5CompositeCAERequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportHDF5CompositeCAE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.acp.v0.model.ObjectService/ImportHDF5CompositeCAE',
            ansys_dot_api_dot_acp_dot_v0_dot_model__pb2.ImportHDF5CompositeCAERequest.SerializeToString,
            ansys_dot_api_dot_acp_dot_v0_dot_base__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
