# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk/core/source.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kaikosdk.core import source_data_pb2 as sdk_dot_core_dot_source__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sdk/core/source.proto\x12\x08kaikosdk\x1a\x1asdk/core/source_data.proto\";\n\x06Source\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.kaikosdk.SourceData\x12\r\n\x05price\x18\x02 \x01(\tBS\n\x12\x63om.kaiko.sdk.coreP\x01Z+github.com/kaikodata/kaiko-go-sdk/core;core\xaa\x02\rKaikoSdk.Coreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk.core.source_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.kaiko.sdk.coreP\001Z+github.com/kaikodata/kaiko-go-sdk/core;core\252\002\rKaikoSdk.Core'
  _globals['_SOURCE']._serialized_start=63
  _globals['_SOURCE']._serialized_end=122
# @@protoc_insertion_point(module_scope)
