# Generated by Django 5.2 on 2025-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0005_alter_openaifile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openaifile",
            old_name="original_file_name",
            new_name="name",
        ),
    ]
