# Generated by Django 5.2 on 2025-06-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0024_alter_vectorstore_files"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assistant",
            constraint=models.UniqueConstraint(
                fields=("name", "model"), name="unique_name_model"
            ),
        ),
    ]
