# Generated by Django 5.2 on 2025-07-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0031_thread_quser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="quser",
        ),
        migrations.AlterField(
            model_name="thread",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_ragamuffin.quser",
            ),
        ),
    ]
