# Generated by Django 5.2.3 on 2025-06-12 09:26

from django.db import migrations, models

from survey.models.survey import get_default_survey_slug


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="order",
            field=models.PositiveIntegerField(default=100, verbose_name="Order"),
        ),
        migrations.AddField(
            model_name="survey",
            name="properties",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional information",
                verbose_name="Properties",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Short description",
                null=True,
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="properties",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional information",
                verbose_name="Properties",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.TextField(
                blank=True,
                help_text="Hint for the question",
                null=True,
                verbose_name="Hint",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Explanation for the answer",
                null=True,
                verbose_name="Explanation",
            ),
        ),
    ]
