"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from speakeasy.new_openapi.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ChatRequestTypedDict(TypedDict):
    prompt: NotRequired[str]


class ChatRequest(BaseModel):
    prompt: Optional[str] = None


class DataTypedDict(TypedDict):
    content: NotRequired[str]


class Data(BaseModel):
    content: Optional[str] = None


class ChatStreamTypedDict(TypedDict):
    r"""A stream containing chat completion tokens"""

    data: DataTypedDict


class ChatStream(BaseModel):
    r"""A stream containing chat completion tokens"""

    data: Data
