# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.files_v1_api import FilesV1Api


class TestFilesV1Api(unittest.TestCase):
    """FilesV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesV1Api()

    def tearDown(self) -> None:
        pass

    def test_get_files_in_files_area(self) -> None:
        """Test case for get_files_in_files_area

        """
        pass

    def test_get_files_in_files_area_0(self) -> None:
        """Test case for get_files_in_files_area_0

        """
        pass

    def test_get_files_in_home_area(self) -> None:
        """Test case for get_files_in_home_area

        """
        pass

    def test_get_files_in_home_area_0(self) -> None:
        """Test case for get_files_in_home_area_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
