# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.organizations_v1_api import OrganizationsV1Api


class TestOrganizationsV1Api(unittest.TestCase):
    """OrganizationsV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsV1Api()

    def tearDown(self) -> None:
        pass

    def test_get_orgs(self) -> None:
        """Test case for get_orgs

        """
        pass


if __name__ == '__main__':
    unittest.main()
