from typing import Any

class EscancianoLobato:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def statistic(self) -> float: ...
    @property
    def pvalue(self) -> float: ...
