# coding: utf-8

"""
    Fastify Template API

    API documentation using Swagger

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keplar_api.models.project_panel_respondent_attribute import ProjectPanelRespondentAttribute

class TestProjectPanelRespondentAttribute(unittest.TestCase):
    """ProjectPanelRespondentAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectPanelRespondentAttribute:
        """Test ProjectPanelRespondentAttribute
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectPanelRespondentAttribute`
        """
        model = ProjectPanelRespondentAttribute()
        if include_optional:
            return ProjectPanelRespondentAttribute(
                qualifications = [
                    keplar_api.models.project_panel_qualification.ProjectPanelQualification(
                        allowed_option_ids = [
                            null
                            ], 
                        question_id = 1.337, )
                    ],
                quota = 1.337,
                quota_name = ''
            )
        else:
            return ProjectPanelRespondentAttribute(
                qualifications = [
                    keplar_api.models.project_panel_qualification.ProjectPanelQualification(
                        allowed_option_ids = [
                            null
                            ], 
                        question_id = 1.337, )
                    ],
                quota = 1.337,
                quota_name = '',
        )
        """

    def testProjectPanelRespondentAttribute(self):
        """Test ProjectPanelRespondentAttribute"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
