export const randomPlankterName = () => {
  const names = [
    "Phytoplankton",
    "Acanthoica quattrospina",
    "Actiniscus pentasterias",
    "Actinoptychus",
    "Alexandrium",
    "Amphidoma caudata",
    "Asterionella glacialis",
    "Asterionellopsis glacialis",
    "Asteromphalus",
    "Bacillaria paxillifer",
    "Bacillaria paxillifera",
    "Bacteriastrum",
    "Bacteriosira fragilis",
    "Bellerochea malleus",
    "Biddulphia alternans",
    "Biddulphia longicruris",
    "Black spine cyst",
    "Blepharocysta paulsenii",
    "Brown cysts",
    "Cerataulina pelagica",
    "Ceratium arcticum",
    "Ceratium arietinum",
    "Ceratium azoricum",
    "Ceratium breve",
    "Ceratium bucephalum",
    "Ceratium candelabrum",
    "Ceratium carriense",
    "Ceratium declinatum",
    "Ceratium divaricatum",
    "Ceratium extensum",
    "Ceratium furca",
    "Ceratium fusus",
    "Ceratium gibberum",
    "Ceratium hexacanthum",
    "Ceratium horridum",
    "Ceratium lamellicorne",
    "Ceratium lineatum",
    "Ceratium longipes",
    "Ceratium macroceros",
    "Ceratium massiliense",
    "Ceratium minutum",
    "Ceratium pentagonum",
    "Ceratium pulchellum",
    "Ceratium teres",
    "Ceratium trichoceros",
    "Ceratium tripos",
    "Ceratium vultur",
    "Chaetoceros Hyalochaete",
    "Chaetoceros Phaeoceros",
    "Cladopyxis",
    "Coccolithaceae",
    "Coccolithus pelagicus",
    "Corethron criophilum",
    "Corethron hystrix",
    "Coscinodiscus concinnus",
    "Coscinodiscus wailesii",
    "Cylindrotheca closterium",
    "Cystodinium",
    "D-sacculus",
    "D-tripos",
    "Dactiliosolen",
    "Dactyliosolen antarcticus",
    "Dactyliosolen fragilissimus",
    "Dactyliosolen mediterraneus",
    "Detonula confervacea",
    "Detonula pumila",
    "Detonula/Neodenticula temporary",
    "Dinoflagellate cysts",
    "Dinophyceae unidentified",
    "Dinophysis acuminata",
    "Dinophysis acuta",
    "Dinophysis caudata",
    "Dinophysis fortii",
    "Dinophysis norvegica",
    "Dinophysis rotundata",
    "Dinophysis",
    "Ditylum brightwellii",
    "Emiliania huxleyi type",
    "Ephemera planamembranacea",
    "Eucampia groenlandica",
    "Eucampia",
    "Eucampia zodiaca",
    "Exuviaella",
    "Filamentous algae",
    "Fragilaria",
    "Fragilariopsis",
    "Glenodinium",
    "Gonyaulax grindleyi",
    "Gonyaulax",
    "Guinardia cylindrus",
    "Guinardia delicatula",
    "Guinardia flaccida",
    "Guinardia striata",
    "Gymnodinium",
    "Gyrosigma",
    "Hemiaulus",
    "Hexasterias problematicus",
    "Hyalochaete resting spore",
    "Lauderia annulata",
    "Lauderia borealis",
    "Leptocylindrus danicus",
    "Leptocylindrus mediterraneus",
    "Lioloma pacificum",
    "Lithodesmium undulatum",
    "Membraneis",
    "Navicula planamembranacea",
    "Navicula",
    "Neodenticula seminae",
    "Nitzschia bicapitata",
    "Nitzschia delicatissima",
    "Nitzschia longissima",
    "Nitzschia seriata",
    "Noctiluca scintillans",
    "Odontella aurita",
    "Odontella longicruris",
    "Odontella obtusa",
    "Odontella rhombus",
    "Odontella sinensis",
    "Operculodinium centrocarpum cysts",
    "Oscillatoria",
    "Oxytoxum",
    "Pachysphaera",
    "Paralia sulcata",
    "Phaeocystis pouchetii",
    "Phalacroma",
    "Phalocroma rotundatum",
    "Pinus pollen",
    "Planktoniella sol",
    "Podolampus",
    "Podosira stelliger",
    "Podosira stelligera",
    "Polykrikos kofoidii cysts",
    "Polykrikos schwartzii cysts",
    "Proboscia alata",
    "Proboscia curvirostris",
    "Proboscia indica",
    "Proboscia inermis",
    "Prorocentrum micans",
    "Prorocentrum",
    "Protoperidinium",
    "Pseudo-nitzschia delicatissima complex",
    "Pseudo-nitzschia seriata",
    "Pseudoeunotia doliolus",
    "Pseudosolenia calcar-avis",
    "Pterosperma ‘blocks IV’",
    "Pterosperma marginatum",
    "Pterosperma polygonum",
    "Pterosperma rotunda",
    "Pterosperma",
    "Pterosperma vanhoeffenii",
    "Pyrophacus",
    "Rhabdosphaera clavigera",
    "Rhaphoneis amphiceros",
    "Rhisosolenia pungens",
    "Rhizomonas setigera",
    "Solenicola setigera",
    "Rhizosolenia acuminata",
    "Rhizosolenia alata alata",
    "Rhizosolenia alata curvirostris",
    "Rhizosolenia alata indica",
    "Rhizosolenia alata inermis",
    "Rhizosolenia bergonii",
    "Rhizosolenia calcar-avis",
    "Rhizosolenia delicatula",
    "Rhizosolenia fragilissima",
    "Rhizosolenia hebetata hiemalis",
    "Rhizosolenia hebetata semispina",
    "Rhizosolenia imbrica. shrubsolei",
    "Rhizosolenia imbricata",
    "Rhizosolenia setigera",
    "Rhizosolenia",
    "Rhizosolenia stolterfothii",
    "Rhizosolenia styliformis",
    "Schroederella delicatula",
    "Scrippsiella",
    "Scripsiella cysts",
    "Silicoflagellatae",
    "Skeletonema costatum",
    "small centric diatom",
    "Spiniferites cysts",
    "Stephanopyxis",
    "Syracosphaera pulchra",
    "Thalassionema nitzschioides",
    "Thalassiosira",
    "Thalassiothrix longissima",
    "Thalassiothrix mediterranea",
    "Trichodesmium",
    "Coscinodiscus",
    "Nitzschia",
    "Zooplankton",
    "Acantharia",
    "Acanthostomella norvegica",
    "Acartia danae",
    "Acartia longiremis",
    "Acartia",
    "Acartia tonsa",
    "Acartia tumida",
    "Alteutha",
    "Amphipod",
    "appendicularia",
    "Atlanta",
    "Atlanta/Oxygyrus",
    "Bivalvia larvae",
    "Branchiostoma lanceolatum",
    "Calanus hyperboreus",
    "Calanus marshallae",
    "Calanus pacificus",
    "Atlantic-fin hel glac",
    "Calocalanus",
    "Candacia armata",
    "Candacia bipinnata",
    "Candacia colombiae",
    "Candacia ethiopica",
    "Candacia pachydactyla",
    "Candacia pacifica",
    "Carinaria",
    "Centropages abdominalis",
    "Centropages bradyi",
    "Cephalopoda larvae",
    "Chaetognatha Adult",
    "Chaetognatha juvenile",
    "Cirripede cypris",
    "Cirripede nauplii",
    "cirrpede larva",
    "Clausocalanus",
    "Clio",
    "Clione limacina",
    "Clione/Thliptodon",
    "Clytemnestra",
    "Clytemnestridae",
    "Cnidaria tissue",
    "Codonella",
    "Codonellopsis",
    "Colonial Radiolaria",
    "Copepod eggs",
    "Copepod nauplii",
    "Corolla-like mollusc",
    "Corycaeus",
    "Ctenocalanus",
    "Ctenocalanus vanus",
    "Cumacean",
    "Cyphocaris",
    "Cyphonautes larva",
    "Dadayiella",
    "Decapod megalopa",
    "Decapod zooea",
    "Decapoda larvae",
    "Dictyocysta",
    "Doliolidae",
    "Echinoderm larvae",
    "Echinoderm post-larvae",
    "Echinospira larvae",
    "Epilabidocera amphrites",
    "Epilabidocera spp",
    "Eucalanidae",
    "Eucalanus attenuatus",
    "Eucalanus bungii",
    "Eucalanus elongatus",
    "Eucalanus pileatus",
    "Euchaeta acuta",
    "Euchaeta hebes",
    "Euchaeta media",
    "Euchaetidae",
    "Euchirella pseudopulchra",
    "Euchirella rostrata",
    "Euphausiacea calyptopis",
    "Euphausiacea eggs",
    "Euphausiacea nauplii",
    "Euphausiacea Total",
    "Euphausiid adult",
    "Eurytemora pacifica",
    "Eurytemora spp.unident",
    "Eutintinnus",
    "Evadne",
    "Favella serrata",
    "Favella",
    "Fish eggs",
    "Fish eggs with oil globules",
    "Fish eggs without oil globules",
    "Fish larvae",
    "Foraminifera",
    "Fusopsis sp.",
    "Gaetanus pungens",
    "Gaetanus simplex",
    "Gaetanus",
    "Gaetanus tenuispinis",
    "Gammaridea",
    "Grainy fried egg",
    "Harpacticoida Total",
    "Helicostomella",
    "Heterorhabdus papilliger",
    "heterorhabdus robustus",
    "Heterorhabdus tanneri",
    "Heterostylites longicornis",
    "Hydroids",
    "Hyperiidea",
    "Ischnocalanus",
    "Isopoda",
    "Juvenile Euphausiid",
    "Lamellibranch larvae",
    "Larvacea",
    "Lepas cypris",
    "Lepas nauplii",
    "Limacina helicina",
    "Lucicutia",
    "Lucifer",
    "Macrosetella gracilis",
    "Mecynocera clausi",
    "Mesocalanus tenuicornis",
    "Mesocalanus tenuicornis",
    "Metridia",
    "Metridia longa",
    "Metridia Okhotensis",
    "Metridia pacifica",
    "Microcalanus",
    "Microniscus larvae of isopod",
    "Microsetella",
    "Mysidacea",
    "Nannocalanus minor",
    "Neocalanus cristatus",
    "Neocalanus cristatus",
    "Neocalanus flemingeri",
    "Neocalanus gracilis",
    "Neocalanus plumchrus",
    "Neocalanus plumchrus/flemingeri",
    "NULLAetideus",
    "Oikopleura",
    "Oithona",
    "Oncaea",
    "Ostracoda",
    "Other eyecount copepods",
    "Para-pseudocalanus",
    "Paracalanus",
    "Paracineta",
    "Paraeuchaeta elongata",
    "Paraeuchaeta glacialis",
    "Paraeuchaeta norvegica",
    "Paraeuchaeta",
    "Parafavella gigantea",
    "Parafavella",
    "Parasitic Nematoda",
    "Parundella",
    "Peraclis",
    "Phronima",
    "Pleuromamma abdominalis",
    "Pleuromamma borealis",
    "Pleuromamma gracilis",
    "Pleuromamma robusta",
    "Pleuromamma",
    "Pleuromamma xiphias",
    "Pneumoderma",
    "Podon",
    "Polychaeta larvae",
    "Pontella pulvinata",
    "Pontellid",
    "Porcellana zooea",
    "Proplectella",
    "Pseudocalanus Adult Pacific",
    "Pseudocalanus sp. adult",
    "Pseudolubbockia dilatata",
    "Ptychocylis",
    "Pycnogonid",
    "Radiolaria",
    "Radiolaria",
    "Rhabdonella",
    "Rhincalanus cornutus",
    "Rhincalanus gigas total",
    "Rhincalanus gigas unstaged",
    "Rhincalanus nasutus",
    "Rotifer eggs",
    "Salpidae",
    "Sapphirina",
    "Scaphocalanus echinatus",
    "Scolecithricella",
    "Scolecithrix spp",
    "Sergestidae",
    "Siphonophora",
    "Siphonostomatoida",
    "Spiny egg",
    "Candacia armata egg",
    "Stenosemella",
    "Stenosemella",
    "Temora discaudata",
    "Temora stylifera",
    "Thalia democratica",
    "Thaliacea",
    "Thliptodon",
    "Tintinna total",
    "Tintinnida cyst",
    "Tintinnida Total",
    "Tintinnidae",
    "Tintinnopsis",
    "Tomopteris",
    "Tortanus discaudatus",
    "Undeuchaeta bispinosa",
    "Undeuchaeta major",
    "Undeuchaeta plumosa",
    "Candacia",
    "Centropages",
    "Eucalanus",
    "Euchaeta",
    "Euchirella",
    "Gymnosomata",
    "Heterorhabdus",
    "mollusca",
    "Pleuromamma"
  ];
  return names[Math.floor(Math.random() * names.length)];
};
