# Generated by Django 5.2.4 on 2025-08-07 16:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='containerjob',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message from failed launch attempt', null=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='last_error_at',
            field=models.DateTimeField(blank=True, help_text='When the last error occurred', null=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='launched_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When job container was actually launched', null=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum launch attempts before giving up'),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='priority',
            field=models.IntegerField(default=50, help_text='Job priority (0-100, higher numbers = higher priority)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='queued_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When job was added to queue for execution', null=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of launch attempts made'),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='retry_strategy',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('aggressive', 'Aggressive'), ('conservative', 'Conservative'), ('high_priority', 'High Priority')], help_text='Retry strategy to use for this job', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='containerjob',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When job should be launched (for scheduled execution)', null=True),
        ),
        migrations.AlterField(
            model_name='containerjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('launching', 'Launching'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='containerjob',
            index=models.Index(fields=['queued_at', 'launched_at'], name='cjob_queue_launched_idx'),
        ),
        migrations.AddIndex(
            model_name='containerjob',
            index=models.Index(fields=['scheduled_for', 'queued_at'], name='cjob_scheduled_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='containerjob',
            index=models.Index(fields=['queued_at', 'retry_count'], name='cjob_queue_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='containerjob',
            index=models.Index(fields=['priority', 'queued_at'], name='cjob_priority_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='containerjob',
            index=models.Index(fields=['status', 'queued_at'], name='cjob_status_queue_idx'),
        ),
    ]
