from __future__ import annotations
from typing import Any, Optional, List, Type, TypeVar, Tuple, Union
import numpy as np
from numpy.typing import NDArray

T = TypeVar('T')


class AngleType:
    AxisAngle: int = ...
    Euler: int = ...

class AnimWrap:
    Clamp: int = ...
    Loop: int = ...
    Reverse: int = ...

class FaceType:
    ARKit: int = ...
    SmplX: int = ...

class FollowerType:
    Cam: int = ...
    CamAndLights: int = ...
    Lights: int = ...

class Gender:
    Female: int = ...
    Male: int = ...
    Neutral: int = ...

class GltfCompatibilityMode:
    Smpl: int = ...
    Unreal: int = ...

class HandType:
    Curled: int = ...
    Fist: int = ...
    Flat: int = ...
    Relaxed: int = ...

class SmplType:
    Smpl: int = ...
    SmplH: int = ...
    SmplPP: int = ...
    SmplX: int = ...
    Supr: int = ...

class UpAxis:
    Y: int = ...
    Z: int = ...

