# flake8: noqa
from keplemon.elements import TLE

class TLECatalog:
    count: int
    name: str | None
    def __init__(self) -> None: ...
    @classmethod
    def from_tle_file(cls, filename: str) -> TLECatalog: ...
    def add(self, tle: TLE) -> None: ...
    def get(self, satellite_id: int) -> TLE: ...
    def remove(self, satellite_id: int) -> None: ...
    def keys(self) -> list[int]: ...
    def get_count(self) -> int: ...
    def clear(self) -> None: ...
    def __getitem__(self, satellite_id: int) -> TLE: ...
