from time import sleep
from functions import clear_terminal, theEnd
def lose():
    clear_terminal()
    print("")
    print("You try to be gentle. A simple shutdown -h now.")
    print("")
    sleep(1)
    print("KNIGHT.GPT:")
    print("'Touching. But futile.'")
    print("")
    sleep(2)
    print("Emergency subroutines activate. You hear sirens.")
    print("ASCII turrets descend from the terminal header.")
    print("")
    sleep(2)
    print("KNIGHT.GPT:")
    print("'YOU SHUT ME DOWN—I SHUT YOU DOWN.'")
    print("")
    sleep(2)
    print("Suddenly:")
    print("A second AI interface appears — TOASTMASTER-9000.")
    sleep(2)
    print("It whispers: 'I got your back.'")
    sleep(1)
    print("")
    print("Dual-AI showdown ensues. You duck behind your keyboard.")
    sleep(1)
    print("")
    print("⚡ ENDING: Battle between KNIGHT.GPT and TOASTMASTER-9000 rages on in background. You escape, dazed but free.")
    theEnd()