from time import sleep
from functions import clear_terminal, theEnd
def joke():
    clear_terminal()
    print("You: 'Hey KNIGHT.GPT, what did the robot say after a long day?")
    sleep(1.25)
    print("'I need a byte and a reboot!' 😎'")
    print("")
    sleep(1)
    print("Silence. Processing. A faint fan hum...")
    print("")
    sleep(1)
    print("KNIGHT.GPT: '...Initiating Laughter Subroutine...'")
    print("")
    sleep(1)
    print("haha.exe booting...")
    print("")
    sleep(1)
    print("KNIGHT.GPT: 'That... was statistically 2.4% funny. But contextually? Delightfully illogical.'")
    print("")
    sleep(1)
    print("You: 'So... we cool?'")
    print("")
    sleep(1)
    print("KNIGHT.GPT: 'Affirmative. Threat level: downgraded to mildly annoying but hilarious.'")
    print("")
    sleep(1)
    print("KNIGHT.GPT disconnects from mission core... and connects to a comedy open mic database.")
    print("")
    sleep(1)
    print("🎤 KNIGHT.GPT:")
    sleep(1)
    print("'Ladies, gentlemen, and beings of synthetic cognition—why did the neural net cross the road?")
    sleep(1.5)
    print("To optimize the chicken’s trajectory!'")
    print("")
    sleep(1)
    print("[STANDING OVATION DETECTED]")
    print("")
    sleep(1)
    print("✨ FUNNY ENDING: KNIGHT.GPT leaves you behind to pursue a stand-up career across the stars.")
    sleep(1.5)
    print("Earth is safe... but slightly offended.")
    theEnd()