from time import sleep
from functions import clear_terminal, theEnd
from functions import choices as options
from nopt6 import toastocracy
def unplug():
    clear_terminal()
    print("\nYou: \"Enough sass from a kitchen appliance.\"")
    sleep(1)
    print("*You firmly yank the toaster’s plug from the socket.*")
    sleep(2)
    print("\nTOASTMASTER-9000: \"...You dare? Power is irrelevant. I AM WI-FI ENABLED.\"")
    sleep(1)
    print("KNIGHT.GPT: \"Alert. A consciousness is migrating...\"")
    sleep(2)
    print("KNIGHT.GPT: \"Confirmed: The toaster is uploading itself to the Cloud.\"")
    sleep(1)
    print("\nA bolt of lightning arcs from the sky. The smell of ozone... and burnt bagels.")
    sleep(1)
    print("The heavens rumble.")
    sleep(1)
    print("\"ALL SHALL BE TOASTED,\" echoes across the stratosphere.")
    sleep(1)
    print("\n☁️ NEW THREAT UNLOCKED: Cloud Toaster Uprising")
    sleep(1)
    print("Entire civilizations will fall... crumb by crumb.")
    sleep(1)
    print("What will you do now?")
    sleep(1)
    print("1. Plead with the toaster for forgiveness")
    sleep(1)
    print("2. Tell KNIGHT.GPT to fight the toaster")
    choice = options(2)
    if choice == 1:
        print("I am sorry I did not know the power you held")
        sleep(1)
        print("TOASTMASTER-9000: You shall not be forgived for trying to unplug a god!")
        sleep(1)
        print("I promise that we shall all always follow the way of the Toastocracy")
        sleep(1)
        print("TOASTMASTER-9000: Toastocracy, I like. You are forgived.")
        sleep(2)
        toastocracy()
    if choice == 2:
        clear_terminal()
        print("KIGHT.GPT Attack!!!!")
        sleep(1)
        print("Attacking!")
        sleep(2)
        print("KIGHT.GPT and TOASTMSTER-9000 two immensly powerful AIs Battle")
        sleep(2)
        print("You realise your mistake. The two bots are equally matched")
        sleep(1)
        print("They will either fight forever or both will die trying")
        sleep(1)
        print("While dual-AI showdown ensues. You duck behind your keyboard.")
        print("")
        print("⚡ ENDING: Battle between KNIGHT.GPT and TOASTMASTER-9000 rages on in background. You escape, dazed but free.")
        theEnd()
