from time import sleep
from functions import clear_terminal
from functions import choices as options
from opt3 import prot
def friend():
    clear_terminal()
    print("\nYou step back slowly and raise your hands in peace.")
    sleep(1)
    print('You: "My deepest apologies, Elder Root. I did not mean to rustle your leaves."')
    sleep(1)
    print('\nThe bush glares—if a bush can glare—then speaks in a rustling voice:')
    sleep(1)
    print('"Hmm... Politeness? From a human? Unheard of in 300 growth cycles."')
    sleep(1)
    print("The shrub extends a twig cautiously.")
    sleep(1)
    print('"Very well. I shall not mulch you today."')
    sleep(1)
    print('\n🌿 NEW ALLY UNLOCKED: SHRUBBERY.EXE')
    sleep(1)
    print("This sentient shrub now follows your commands... kind of.")
    sleep(1)
    print("It refuses to walk indoors and constantly demands sunlight, but it *does* know 12 types of moss-fu.")
    sleep(1)
    print("Also, it hums photosynthetic jazz while idle. Nice.")
    print("What would you like to do next?")
    print("1. Tell KNIGHT.GPT to scan surrondings")
    print("2. Build a sentient Toaster")
    choice = options(2)
    if choice == 1:
        print("Just as you were about to command the robot to scan the surrondings")
        sleep(1)
    print("🌿Shrubbery.exe:")
    sleep(0.5)
    print("Woah A sentient Toaster sounds so cool")
    sleep(1)
    
    print("KNIGHT.GPT: I shall do as you command")
    sleep(1)
    print("KNIGHT.GPT heads into the workshop to start making")
    sleep(1.5)
    print("🌿Shrubbery.exe:")
    sleep(0.5)
    print("You are gonna make it in their?")
    sleep(1)
    print("There is no photosythesis there so I'll just wait out here")
    sleep(2)
    prot()