from setuptools import setup, find_packages

setup(
    name='spamosaic',
    version='1.0.2',
    author='Jinmiao Lab',
    author_email='3200376951@qq.com',
    description='SpaMosaic: Mosaic Integration of Spatial Multi-omics',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/JinmiaoChenLab/SpaMosaic',
    packages=find_packages(),
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    install_requires=[
        'anndata>=0.9.2',
        'annoy>=1.17.3',
        'h5py>=3.10.0',
        'harmony-pytorch>=0.1.7',
        'hnswlib>=0.8.0',
        'matplotlib>=3.7.4',
        'networkx>=3.1',
        'numpy>=1.22.4',
        'pandas>=1.5.3',
        'PyYAML>=6.0.1',
        'scanpy>=1.9.6',
        'scikit-learn>=1.3.2',
        'scipy>=1.10.1',
        'seaborn>=0.12.2',
        'tqdm>=4.66.1',
    ],
    python_requires='>=3.8',
)
