from .controls.controls import *
from .controls.MyCatechismControl import *
from .controls.MyModelControl import *
from .controls.MyModelAndVideosControl import *
from .controls.MyProjectControl import *
from .controls.MyScriptControl import *
from .controls.MyVoiceControl import *
from .controls.MyVoiceModelControl import *
from .controls.NewsAttachmentsControl import *
from .controls.NewsControl import *
from .models.models import *
from .tools.createTables import *